version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: exchange_rate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080" #api
      - "8081:8081" #grpc
